### ISSUE TITLE
 Non-ASCII character '\xc3' in file pymp2rage/mp2rage.py on line 475

### ISSUE THREAD

**Issue by 0rC0** [Gilles86/pymp2rage#1]
there is some problem at line 474 with the è of José

```
$ python
Python 2.7.15 | packaged by conda-forge | (default, Jul 27 2018, 10:26:36) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymp2rage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymp2rage/__init__.py", line 1, in <module>
    from .mp2rage import MP2RAGE, MEMP2RAGE
  File "pymp2rage/mp2rage.py", line 474
SyntaxError: Non-ASCII character '\xc3' in file pymp2rage/mp2rage.py on line 475, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by Gilles86** [comment]
Good catch. I solved it in this commit
https://github.com/Gilles86/pymp2rage/commit/715b087355ad00affee3b3cbc2a52c8f57815f35

pymp2rage is still under development. Can I ask what you are using it for? :) Just curious

**Comment by 0rC0** [comment]
Yes you can :)

I'm working with some mp2rage images and no tool give me a satisfying skull stripping.

I wanted to estimate a T1 map to use with [nighres](https://github.com/nighres/nighres), using only T1w and second inversion I obtain not a good result.

**Comment by Gilles86** [comment]
> I wanted to estimate a T1 map to use with nighres, using only T1w and second inversion I obtain not a good result.

That is notoriously hard and I am afraid that nighres won't actually use the T1 map for determining the border of the skull. It will just mask it based on where it puts the brain in the INV2.

A hack that worked well for us is to pull the INV2 through ANTS's N4BiasFieldCorrection and then multiply this corrected INV2 with the T1w image. This product image you can then throw through general purpose brain extraction tools like FSL's BET.

Cheers

**Comment by 0rC0** [comment]
Thank very much for the trick!
I used it with FreeSurfer for the brain extraction (I ran autorecon1) and the results are really better!
