### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ofgulban** [Gilles86/pymp2rage#2]
Hi @Gilles86 , thanks for this repository. 

I see `version.py` indicating `MIT` license but I cannot see the `LICENSE` file. Am I correct to assume that the license is `MIT`?
It might be useful to indicate the license in the readme and add `LICENSE.md` so that github shows it on the 'about panel' too.

**Comment by Gilles86** [comment]
Hi Omer,

Thanks! Great to hear that this might be useful to you.

I don't care too much about this license stuff, but of course it's important. I really quickly googled a bit and decided to go with the Apache license. I now included a `LICENSE` file and updated the metadata of the setup-scripts.

**Comment by ofgulban** [comment]
@Gilles86 thanks for the quick response!

I am going to derive a minimal T1 fitting command line interface from your code. It is great help that you have converted Marques's Matlab code already :).

By the way, I was confused about `bids` library you are using. I could not find where to get it from. Just wanted to let you know.

**Comment by Gilles86** [comment]
Ah, that is `pybids`, a library to easily access BIDS datasets:
https://github.com/bids-standard/pybids

Unfortunately, the API of `bids` tended to change quite a bit from time to time, which kinda made me give up making it work.

Are you familiar with BIDS and our [recent efforts to standardize qMRI datasets, specifically MP2RAGE(-ME) data](https://neurostars.org/t/pull-request-bep-001-into-main-bids-specification-support-for-quantitative-mri-in-bids/7268)?

Would be great if you could incorporate your command line app into the `pymp2rage`-package (e.g., put it in the `bin`-folder or something)! Please let me know if I can help with anbything.

**Comment by ofgulban** [comment]
I see, so they just changed it from `bids` to `pybids`.

I am familiar with BIDS. Maybe we can discuss again how to proceed with BIDS after I do my changes.

I am going to make drastic changes in the structure of your repo. & functions because the functionality that I have in mind (similarly structured project [here](https://github.com/ofgulban/iphigen), see command line + scripting examples). So maybe you can have a look at it when it is done and see if you like it and whether want to merge back some parts of it to here etc.

**Comment by Gilles86** [comment]
Cool.

Well let'see. Please keep me posted :).
